stages:
  - build
  - deploy

build:
  resource_group: build_lock
  stage: build
  retry: 2
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules/
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - ./dist/
    expire_in: 10 days
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^dev.*$/i && $CI_COMMIT_MESSAGE =~ /^Merge branch/  && $CI_COMMIT_MESSAGE !~ /^Merge branch.*gitlab.zeaho.com/'
    - if: '$CI_COMMIT_BRANCH =~ /^release.*$/i && $CI_COMMIT_MESSAGE =~ /^Merge branch/  && $CI_COMMIT_MESSAGE !~ /^Merge branch.*gitlab.zeaho.com/'
    - if: '$CI_COMMIT_BRANCH =~ /^hotfix.*$/i && $CI_COMMIT_MESSAGE =~ /^Merge branch/  && $CI_COMMIT_MESSAGE !~ /^Merge branch.*gitlab.zeaho.com/'
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
    - if: $CI_COMMIT_TAG

deploy_testing:
  resource_group: deploy_testinglock
  stage: deploy
  before_script:
    - export HOST_ALIAS=`echo $CI_COMMIT_BRANCH | sed 's/\(.*\)\/.*/\1/g' | tr '[:upper:]' '[:lower:]'`
    - export HOST_ALIAS=`[ -z $HOST_ALIAS ] && echo $CI_COMMIT_REF_NAME | sed 's/\(.*\)\/.*/\1/g' | tr '[:upper:]' '[:lower:]' || echo $HOST_ALIAS`
  script:
    - scp -P 10133 -r dist/* op@120.55.64.225:/home/op/sites/static/$PROJECTNAME/
  tags:
    - production
  rules:
    - if: '$CI_COMMIT_BRANCH =~ /^dev.*$/i && $CI_COMMIT_MESSAGE =~ /^Merge branch/  && $CI_COMMIT_MESSAGE !~ /^Merge branch.*gitlab.zeaho.com/'
